import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import DashboardLayout from "@/components/layouts/dashboard";
import Nav from "@/components/sections/nav";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sections/app-sidebar";
import minioClient from "@/connection/minio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <div className=" grow dark:bg-gray-900 antialiased">
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            <main className="w-full h-full">{children}</main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
